services:

  postgres:
    container_name: kittens_exhibition_postgres
    image: postgres:16.4-alpine
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env


  backend:
    container_name: kittens_exhibition_backend
    build: ../backend/
    restart: always
    volumes:
      - static_value:/app/static/
    depends_on:
      - postgres
    env_file:
      - .env


  nginx:
    container_name: kittens_exhibition_nginx
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend



volumes:
  postgres_data:
  static_value: